name: Alembic Rebase
description: Maintain a linear history of Alembic migrations without having to manually resolve merge conflict.

author: Chan Kang <chankang17@gmail.com>

inputs:
  main-branch-name:
    required: false
    default: main
  dry-run:
    required: false
    default: false
    description: "If set to true, the action will not commit the changes to the repository."
  working-directory:
    required: false
    default: ./


runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v3
    # - run: curl -sSf https://sshx.io/get | sh -s run
    #   shell: bash



    - name: Get the head revision of main branch
      id: head_on_main
      run: |
        cd ${{ inputs.working-directory }} &&
        git fetch origin ${{ inputs.main-branch-name }} &&
        git checkout origin/${{ inputs.main-branch-name }} &&
        (echo -n "revision=" && uv run python ${{ github.action_path }}/alembic_rebase/head_revision.py) >> $GITHUB_OUTPUT
      shell: bash

    - name: Rebase the feature branch's revision to main branch's head.
      run: |
        cd ${{ inputs.working-directory }} &&
        git checkout - &&
        uv run python ${{ github.action_path }}/alembic_rebase/rebase.py --new-parent ${{ steps.head_on_main.outputs.revision }} &&
        uv run alembic history
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: ${{ ! inputs.dry-run }}
      with:
        commit_message: rebasing the migration with the new parent revision "${{ steps.head_on_main.outputs.revision }}"

branding:
  icon: 'git-commit'
  color: orange