name: Alembic Rebase
description: Maintain a linear history of Alembic migrations without having to manually resolve merge conflict.

author: Chan Kang <chankang17@gmail.com>

inputs:
  main-branch-name:
    required: false
    default: main
  alembic-config-path:
    required: false
    default: alembic.ini

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v3

    - id: head_on_main
      run: |
        git fetch origin ${{ inputs.main-branch-name }} &&
        git checkout origin/${{ inputs.main-branch-name }} &&
        (echo -n "revision=" && uv run python ${{ github.action_path }}/head_revision.py --alembic-cfg-path ${{ inputs.alembic-config-path }}) >> $GITHUB_OUTPUT
      shell: bash

    - run: |
        git checkout - &&
        uv run python ${{ github.action_path }}/rebase.py --new-parent ${{ steps.head_on_main.outputs.revision }} --alembic-cfg-path ${{ inputs.alembic-config-path }}
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: rebasing the migration with the new parent revision "${{ steps.head_on_main.outputs.revision }}"

branding:
  icon: 'git-commit'
  color: orange