name: Alembic Rebase
description: Maintain a linear history of Alembic migrations without having to manually resolve merge conflict.

author: Chan Kang <chankang17@gmail.com>

inputs:

outputs:

runs:
  using: "composite"
  steps:
    - run: echo "hello world"

branding:
  icon: 'git-commit'
  color: orange